apiVersion: v1
kind: Service
metadata:
  name: nexus-server-metrics
  namespace: nexus
  labels:
    app.kubernetes.io/name: nexus
    app.kubernetes.io/component: server
    prometheus.io/scrape: "true"
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexus
    app.kubernetes.io/component: server
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
