apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nexus-server.fullname" . }}-tls
  labels:
    {{- include "nexus-server.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt.pem: |
{{ .Values.tls.caCert | indent 4 }}
  server.crt.pem: |
{{ .Values.tls.serverCert | indent 4 }}
  server.key.pem: |
{{ .Values.tls.serverKey | indent 4 }}
