//! COBIT - Control Objectives for Information Technologies
//!
//! IT governance and management framework by ISACA.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the COBIT 2019 framework definition
pub fn create_framework() -> Framework {
    Framework::new("cobit", "COBIT 2019", FrameworkCategory::AuditTrust)
        .with_description("Control Objectives for Information and Related Technologies")
        .with_version("2019")
        .with_url("https://www.isaca.org/resources/cobit")
        // COBIT Governance and Management Objectives
        .with_domain(FrameworkDomain::new("EDM", "Evaluate, Direct and Monitor").with_order(1))
        .with_domain(FrameworkDomain::new("APO", "Align, Plan and Organize").with_order(2))
        .with_domain(FrameworkDomain::new("BAI", "Build, Acquire and Implement").with_order(3))
        .with_domain(FrameworkDomain::new("DSS", "Deliver, Service and Support").with_order(4))
        .with_domain(FrameworkDomain::new("MEA", "Monitor, Evaluate and Assess").with_order(5))
        // EDM - Governance Objectives
        .with_control(Control::new("EDM01", "Ensured Governance Framework Setting and Maintenance")
            .with_description("Analyze and articulate the requirements for governance of enterprise IT")
            .with_domain("EDM").with_priority(5))
        .with_control(Control::new("EDM02", "Ensured Benefits Delivery")
            .with_description("Optimize the value contribution to the business from IT-enabled investments")
            .with_domain("EDM").with_priority(4))
        .with_control(Control::new("EDM03", "Ensured Risk Optimization")
            .with_description("Ensure that IT-related enterprise risk does not exceed risk appetite")
            .with_domain("EDM").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.6.1", "Risk Management", MappingStrength::Moderate)))
        .with_control(Control::new("EDM04", "Ensured Resource Optimization")
            .with_description("Ensure that adequate and sufficient IT-related capabilities are available")
            .with_domain("EDM").with_priority(4))
        .with_control(Control::new("EDM05", "Ensured Stakeholder Engagement")
            .with_description("Ensure stakeholders are supportive of the IT strategy and roadmap")
            .with_domain("EDM").with_priority(3))
        // APO - Management Objectives
        .with_control(Control::new("APO01", "Managed IT Management Framework")
            .with_description("Implement and maintain mechanisms to manage information and technology")
            .with_domain("APO").with_priority(4))
        .with_control(Control::new("APO02", "Managed Strategy")
            .with_description("Provide holistic view of the business and IT environment")
            .with_domain("APO").with_priority(4))
        .with_control(Control::new("APO12", "Managed Risk")
            .with_description("Identify, assess and reduce IT-related risk within tolerance levels")
            .with_domain("APO").with_priority(5)
            .with_mapping(ControlMapping::new("nist_csf", "ID.RA", "Risk Assessment", MappingStrength::Strong)))
        .with_control(Control::new("APO13", "Managed Security")
            .with_description("Define, operate and monitor a system for information security management")
            .with_domain("APO").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.5.1", "Information Security Policies", MappingStrength::Strong)))
        // BAI - Implementation Objectives
        .with_control(Control::new("BAI01", "Managed Programs")
            .with_description("Manage all programs from the investment portfolio")
            .with_domain("BAI").with_priority(4))
        .with_control(Control::new("BAI03", "Managed Solutions Identification and Build")
            .with_description("Establish and maintain identified solutions in line with enterprise requirements")
            .with_domain("BAI").with_priority(4))
        .with_control(Control::new("BAI06", "Managed IT Changes")
            .with_description("Manage all changes in a controlled manner")
            .with_domain("BAI").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.12.1.2", "Change Management", MappingStrength::Strong)))
        .with_control(Control::new("BAI10", "Managed Configuration")
            .with_description("Define and maintain descriptions and relationships of IT assets")
            .with_domain("BAI").with_priority(4))
        // DSS - Service Delivery Objectives
        .with_control(Control::new("DSS01", "Managed Operations")
            .with_description("Coordinate and execute activities required to deliver IT services")
            .with_domain("DSS").with_priority(4))
        .with_control(Control::new("DSS02", "Managed Service Requests and Incidents")
            .with_description("Provide timely and effective response to user requests and incidents")
            .with_domain("DSS").with_priority(4))
        .with_control(Control::new("DSS04", "Managed Continuity")
            .with_description("Establish and maintain a plan to enable business and IT to respond to incidents")
            .with_domain("DSS").with_priority(5)
            .with_mapping(ControlMapping::new("iso22301", "8.4", "Business Continuity", MappingStrength::Strong)))
        .with_control(Control::new("DSS05", "Managed Security Services")
            .with_description("Protect enterprise information to maintain acceptable level of security risk")
            .with_domain("DSS").with_priority(5))
        // MEA - Monitoring Objectives
        .with_control(Control::new("MEA01", "Managed Performance and Conformance Monitoring")
            .with_description("Collect, validate and evaluate business, IT and process goals and metrics")
            .with_domain("MEA").with_priority(4))
        .with_control(Control::new("MEA02", "Managed System of Internal Control")
            .with_description("Monitor and evaluate the internal control environment")
            .with_domain("MEA").with_priority(4))
        .with_control(Control::new("MEA03", "Managed Compliance with External Requirements")
            .with_description("Evaluate that IT processes and IT-supported business processes comply with requirements")
            .with_domain("MEA").with_priority(5))
        .with_control(Control::new("MEA04", "Managed Assurance")
            .with_description("Enable the organization to design and develop efficient assurance initiatives")
            .with_domain("MEA").with_priority(4))
}
