//! DORA - Digital Operational Resilience Act
//!
//! EU regulation for financial sector digital operational resilience.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the DORA framework definition
pub fn create_framework() -> Framework {
    Framework::new("dora", "DORA", FrameworkCategory::Financial)
        .with_description("Digital Operational Resilience Act for Financial Entities")
        .with_version("2022/2554")
        .with_url("https://eur-lex.europa.eu/eli/reg/2022/2554")
        // DORA Pillars
        .with_domain(FrameworkDomain::new("ICT", "ICT Risk Management").with_order(1))
        .with_domain(FrameworkDomain::new("INC", "ICT-related Incident Management").with_order(2))
        .with_domain(FrameworkDomain::new("TEST", "Digital Operational Resilience Testing").with_order(3))
        .with_domain(FrameworkDomain::new("TPR", "ICT Third-Party Risk Management").with_order(4))
        .with_domain(FrameworkDomain::new("ISH", "Information Sharing").with_order(5))
        // ICT Risk Management (Articles 5-16)
        .with_control(Control::new("ICT-1", "ICT Risk Management Framework")
            .with_description("Establish and maintain sound ICT risk management framework")
            .with_domain("ICT").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "6.1", "Risk Management", MappingStrength::Strong)))
        .with_control(Control::new("ICT-2", "Governance and Organization")
            .with_description("Management body shall define and oversee ICT risk management")
            .with_domain("ICT").with_priority(5))
        .with_control(Control::new("ICT-3", "ICT Systems and Tools")
            .with_description("Use and maintain updated ICT systems and tools")
            .with_domain("ICT").with_priority(4))
        .with_control(Control::new("ICT-4", "Identification")
            .with_description("Identify, classify and document ICT supported business functions and assets")
            .with_domain("ICT").with_priority(5)
            .with_mapping(ControlMapping::new("nist_csf", "ID.AM", "Asset Management", MappingStrength::Strong)))
        .with_control(Control::new("ICT-5", "Protection and Prevention")
            .with_description("Implement ICT security policies and measures for protection")
            .with_domain("ICT").with_priority(5))
        .with_control(Control::new("ICT-6", "Detection")
            .with_description("Implement mechanisms to detect anomalous activities")
            .with_domain("ICT").with_priority(5)
            .with_mapping(ControlMapping::new("nist_csf", "DE.CM", "Continuous Monitoring", MappingStrength::Strong)))
        .with_control(Control::new("ICT-7", "Response and Recovery")
            .with_description("Implement ICT business continuity policy")
            .with_domain("ICT").with_priority(5))
        .with_control(Control::new("ICT-8", "Backup Policies")
            .with_description("Implement backup and recovery policies and procedures")
            .with_domain("ICT").with_priority(5))
        .with_control(Control::new("ICT-9", "Learning and Evolving")
            .with_description("Continuously learn and evolve from ICT incidents")
            .with_domain("ICT").with_priority(4))
        .with_control(Control::new("ICT-10", "Communication")
            .with_description("Develop crisis communication plans")
            .with_domain("ICT").with_priority(4))
        // ICT-Related Incident Management (Articles 17-23)
        .with_control(Control::new("INC-1", "Incident Management Process")
            .with_description("Establish ICT-related incident management process")
            .with_domain("INC").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.16.1", "Incident Management", MappingStrength::Strong)))
        .with_control(Control::new("INC-2", "Incident Classification")
            .with_description("Classify ICT-related incidents according to criteria")
            .with_domain("INC").with_priority(4))
        .with_control(Control::new("INC-3", "Major Incident Reporting")
            .with_description("Report major ICT-related incidents to competent authorities")
            .with_domain("INC").with_priority(5))
        .with_control(Control::new("INC-4", "Incident Notification")
            .with_description("Notify clients of significant incidents affecting their data")
            .with_domain("INC").with_priority(4))
        .with_control(Control::new("INC-5", "Incident Root Cause Analysis")
            .with_description("Conduct post-incident reviews for major incidents")
            .with_domain("INC").with_priority(4))
        // Digital Operational Resilience Testing (Articles 24-27)
        .with_control(Control::new("TEST-1", "Testing Program")
            .with_description("Establish comprehensive digital operational resilience testing program")
            .with_domain("TEST").with_priority(5))
        .with_control(Control::new("TEST-2", "Vulnerability Assessments")
            .with_description("Conduct regular vulnerability assessments and scans")
            .with_domain("TEST").with_priority(5)
            .with_mapping(ControlMapping::new("pci_dss", "11.3", "Penetration Testing", MappingStrength::Strong)))
        .with_control(Control::new("TEST-3", "Scenario-Based Testing")
            .with_description("Conduct scenario-based testing including stress testing")
            .with_domain("TEST").with_priority(4))
        .with_control(Control::new("TEST-4", "TLPT")
            .with_description("Carry out threat-led penetration testing (TLPT)")
            .with_domain("TEST").with_priority(5))
        .with_control(Control::new("TEST-5", "Testing of ICT Tools")
            .with_description("Test ICT tools and systems before deployment")
            .with_domain("TEST").with_priority(4))
        // ICT Third-Party Risk Management (Articles 28-44)
        .with_control(Control::new("TPR-1", "Third-Party Risk Policy")
            .with_description("Adopt strategy on ICT third-party risk")
            .with_domain("TPR").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.15.1", "Supplier Relationships", MappingStrength::Strong)))
        .with_control(Control::new("TPR-2", "Register of Arrangements")
            .with_description("Maintain register of all ICT third-party arrangements")
            .with_domain("TPR").with_priority(4))
        .with_control(Control::new("TPR-3", "Due Diligence")
            .with_description("Conduct due diligence on prospective ICT third-party providers")
            .with_domain("TPR").with_priority(5))
        .with_control(Control::new("TPR-4", "Contractual Arrangements")
            .with_description("Ensure contracts include required provisions")
            .with_domain("TPR").with_priority(5))
        .with_control(Control::new("TPR-5", "Concentration Risk")
            .with_description("Identify and manage ICT concentration risk")
            .with_domain("TPR").with_priority(4))
        .with_control(Control::new("TPR-6", "Exit Strategies")
            .with_description("Develop and test exit strategies for critical third parties")
            .with_domain("TPR").with_priority(4))
        // Information Sharing (Articles 45)
        .with_control(Control::new("ISH-1", "Threat Intelligence Sharing")
            .with_description("Participate in cyber threat intelligence sharing arrangements")
            .with_domain("ISH").with_priority(3))
        .with_control(Control::new("ISH-2", "Information Exchange Framework")
            .with_description("Establish framework for exchanging threat intelligence")
            .with_domain("ISH").with_priority(3))
}
