//! EU AI Act - European Union Artificial Intelligence Act
//!
//! Regulatory framework for AI systems in the European Union.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the EU AI Act framework definition
pub fn create_framework() -> Framework {
    Framework::new("eu_ai_act", "EU AI Act", FrameworkCategory::Privacy)
        .with_description("European Union Artificial Intelligence Act")
        .with_version("2024")
        .with_url("https://artificialintelligenceact.eu/")
        // Risk Categories
        .with_domain(FrameworkDomain::new("PRO", "Prohibited AI Practices").with_order(1))
        .with_domain(FrameworkDomain::new("HIGH", "High-Risk AI Systems").with_order(2))
        .with_domain(FrameworkDomain::new("LIM", "Limited Risk AI").with_order(3))
        .with_domain(FrameworkDomain::new("MIN", "Minimal Risk AI").with_order(4))
        .with_domain(FrameworkDomain::new("GEN", "General Purpose AI").with_order(5))
        .with_domain(FrameworkDomain::new("GOV", "Governance and Oversight").with_order(6))
        // Prohibited AI Practices (Article 5)
        .with_control(Control::new("PRO-1", "Subliminal Manipulation Ban")
            .with_description("AI systems shall not deploy subliminal techniques to distort behavior")
            .with_domain("PRO").with_priority(5))
        .with_control(Control::new("PRO-2", "Vulnerability Exploitation Ban")
            .with_description("AI systems shall not exploit vulnerabilities of specific groups")
            .with_domain("PRO").with_priority(5))
        .with_control(Control::new("PRO-3", "Social Scoring Ban")
            .with_description("AI systems shall not be used for social scoring by public authorities")
            .with_domain("PRO").with_priority(5))
        .with_control(Control::new("PRO-4", "Biometric Categorization Limits")
            .with_description("Real-time remote biometric identification limited to specific cases")
            .with_domain("PRO").with_priority(5))
        // High-Risk AI Systems (Article 6-51)
        .with_control(Control::new("HIGH-1", "Risk Management System")
            .with_description("Establish, implement, and maintain a risk management system")
            .with_domain("HIGH").with_priority(5)
            .with_mapping(ControlMapping::new("iso42001", "6.1", "AI Risk Management", MappingStrength::Strong)))
        .with_control(Control::new("HIGH-2", "Data Governance")
            .with_description("Training, validation and testing data sets shall meet quality criteria")
            .with_domain("HIGH").with_priority(5)
            .with_mapping(ControlMapping::new("gdpr", "Art.5", "Data Quality", MappingStrength::Strong)))
        .with_control(Control::new("HIGH-3", "Technical Documentation")
            .with_description("Technical documentation shall be drawn up before system is placed on market")
            .with_domain("HIGH").with_priority(4))
        .with_control(Control::new("HIGH-4", "Record-Keeping")
            .with_description("High-risk AI systems shall allow for automatic recording of events (logs)")
            .with_domain("HIGH").with_priority(5))
        .with_control(Control::new("HIGH-5", "Transparency")
            .with_description("High-risk AI systems shall be designed to enable users to understand output")
            .with_domain("HIGH").with_priority(5))
        .with_control(Control::new("HIGH-6", "Human Oversight")
            .with_description("High-risk AI systems shall be designed for effective human oversight")
            .with_domain("HIGH").with_priority(5)
            .with_mapping(ControlMapping::new("iso42001", "8.4", "Human Oversight", MappingStrength::Strong)))
        .with_control(Control::new("HIGH-7", "Accuracy and Robustness")
            .with_description("High-risk AI systems shall achieve appropriate levels of accuracy and robustness")
            .with_domain("HIGH").with_priority(5))
        .with_control(Control::new("HIGH-8", "Cybersecurity")
            .with_description("High-risk AI systems shall be resilient against security threats")
            .with_domain("HIGH").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.12", "Operations Security", MappingStrength::Strong)))
        // Limited Risk AI (Article 52)
        .with_control(Control::new("LIM-1", "Transparency Obligations")
            .with_description("Users shall be informed they are interacting with AI system")
            .with_domain("LIM").with_priority(4))
        .with_control(Control::new("LIM-2", "Emotion Recognition Disclosure")
            .with_description("Inform natural persons exposed to emotion recognition systems")
            .with_domain("LIM").with_priority(4))
        .with_control(Control::new("LIM-3", "Deep Fake Labeling")
            .with_description("Synthetic content shall be labeled as artificially generated")
            .with_domain("LIM").with_priority(4))
        // General Purpose AI (Article 52a-52e)
        .with_control(Control::new("GEN-1", "GPAI Technical Documentation")
            .with_description("Providers of GPAI models shall draw up technical documentation")
            .with_domain("GEN").with_priority(4))
        .with_control(Control::new("GEN-2", "Copyright Compliance")
            .with_description("GPAI providers shall have policy to comply with copyright law")
            .with_domain("GEN").with_priority(4))
        .with_control(Control::new("GEN-3", "Training Data Summary")
            .with_description("GPAI providers shall make available summary of training data content")
            .with_domain("GEN").with_priority(4))
        .with_control(Control::new("GEN-4", "Systemic Risk Assessment")
            .with_description("GPAI models with systemic risk shall perform model evaluation")
            .with_domain("GEN").with_priority(5))
        // Governance
        .with_control(Control::new("GOV-1", "Conformity Assessment")
            .with_description("High-risk AI systems shall undergo conformity assessment")
            .with_domain("GOV").with_priority(5))
        .with_control(Control::new("GOV-2", "CE Marking")
            .with_description("CE marking shall be affixed to high-risk AI systems")
            .with_domain("GOV").with_priority(4))
        .with_control(Control::new("GOV-3", "EU Database Registration")
            .with_description("High-risk AI systems shall be registered in EU database")
            .with_domain("GOV").with_priority(4))
        .with_control(Control::new("GOV-4", "Post-Market Monitoring")
            .with_description("Providers shall establish post-market monitoring system")
            .with_domain("GOV").with_priority(4))
        .with_control(Control::new("GOV-5", "Incident Reporting")
            .with_description("Serious incidents shall be reported to market surveillance authorities")
            .with_domain("GOV").with_priority(5))
}
