//! HITRUST CSF - Health Information Trust Alliance Common Security Framework
//!
//! Healthcare security and privacy framework.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the HITRUST CSF framework definition
pub fn create_framework() -> Framework {
    Framework::new("hitrust", "HITRUST CSF", FrameworkCategory::Healthcare)
        .with_description("Health Information Trust Alliance Common Security Framework")
        .with_version("11.0")
        .with_url("https://hitrustalliance.net/hitrust-csf/")
        // HITRUST Control Categories
        .with_domain(FrameworkDomain::new("00", "Information Security Management Program").with_order(1))
        .with_domain(FrameworkDomain::new("01", "Access Control").with_order(2))
        .with_domain(FrameworkDomain::new("02", "Human Resources Security").with_order(3))
        .with_domain(FrameworkDomain::new("03", "Risk Management").with_order(4))
        .with_domain(FrameworkDomain::new("04", "Security Policy").with_order(5))
        .with_domain(FrameworkDomain::new("05", "Organization of Information Security").with_order(6))
        .with_domain(FrameworkDomain::new("06", "Compliance").with_order(7))
        .with_domain(FrameworkDomain::new("07", "Asset Management").with_order(8))
        .with_domain(FrameworkDomain::new("08", "Physical and Environmental Security").with_order(9))
        .with_domain(FrameworkDomain::new("09", "Communications and Operations Management").with_order(10))
        .with_domain(FrameworkDomain::new("10", "Information Systems Acquisition, Development, and Maintenance").with_order(11))
        .with_domain(FrameworkDomain::new("11", "Information Security Incident Management").with_order(12))
        .with_domain(FrameworkDomain::new("12", "Business Continuity Management").with_order(13))
        .with_domain(FrameworkDomain::new("13", "Privacy Practices").with_order(14))
        // Information Security Management Program
        .with_control(Control::new("00.a", "Information Security Management Program")
            .with_description("Establish, implement, maintain and continually improve ISMP")
            .with_domain("00").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "4.4", "ISMS", MappingStrength::Strong)))
        // Access Control
        .with_control(Control::new("01.a", "Access Control Policy")
            .with_description("Establish access control policy based on business requirements")
            .with_domain("01").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.312(a)(1)", "Access Control", MappingStrength::Strong)))
        .with_control(Control::new("01.b", "User Registration")
            .with_description("Implement formal user registration and de-registration procedure")
            .with_domain("01").with_priority(5))
        .with_control(Control::new("01.c", "Privilege Management")
            .with_description("Restrict and control allocation of privileges")
            .with_domain("01").with_priority(5))
        .with_control(Control::new("01.d", "User Password Management")
            .with_description("Control allocation of passwords through formal management process")
            .with_domain("01").with_priority(4))
        .with_control(Control::new("01.j", "User Authentication")
            .with_description("Require users to authenticate using secure authentication methods")
            .with_domain("01").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "IA-2", "Identification", MappingStrength::Strong)))
        // Risk Management
        .with_control(Control::new("03.a", "Risk Management Program")
            .with_description("Establish comprehensive risk management program")
            .with_domain("03").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.308(a)(1)(ii)(A)", "Risk Analysis", MappingStrength::Strong)))
        .with_control(Control::new("03.b", "Risk Assessment")
            .with_description("Conduct accurate and thorough risk assessments")
            .with_domain("03").with_priority(5))
        .with_control(Control::new("03.c", "Risk Mitigation")
            .with_description("Implement security measures to reduce risks")
            .with_domain("03").with_priority(5))
        // Security Policy
        .with_control(Control::new("04.a", "Information Security Policy")
            .with_description("Publish and communicate information security policy")
            .with_domain("04").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.5.1", "Policies", MappingStrength::Strong)))
        // Compliance
        .with_control(Control::new("06.a", "Legal Requirements")
            .with_description("Identify applicable legal, regulatory requirements")
            .with_domain("06").with_priority(5))
        .with_control(Control::new("06.c", "Protection of Records")
            .with_description("Protect records from loss, destruction, falsification")
            .with_domain("06").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.530(j)", "Retention", MappingStrength::Strong)))
        .with_control(Control::new("06.d", "Data Protection and Privacy")
            .with_description("Ensure privacy and protection of personal data")
            .with_domain("06").with_priority(5))
        // Communications and Operations
        .with_control(Control::new("09.a", "Documented Operating Procedures")
            .with_description("Document operating procedures and make available")
            .with_domain("09").with_priority(4))
        .with_control(Control::new("09.j", "Controls Against Malicious Code")
            .with_description("Implement detection and prevention controls for malicious code")
            .with_domain("09").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "SI-3", "Malicious Code", MappingStrength::Strong)))
        .with_control(Control::new("09.l", "Backup")
            .with_description("Make and test backup copies of information and software")
            .with_domain("09").with_priority(5))
        .with_control(Control::new("09.m", "Network Controls")
            .with_description("Implement network security controls")
            .with_domain("09").with_priority(5))
        .with_control(Control::new("09.s", "Electronic Messaging")
            .with_description("Protect information involved in electronic messaging")
            .with_domain("09").with_priority(4))
        // Incident Management
        .with_control(Control::new("11.a", "Incident Response")
            .with_description("Establish incident response and reporting procedures")
            .with_domain("11").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.308(a)(6)", "Security Incident", MappingStrength::Strong)))
        .with_control(Control::new("11.c", "Breach Notification")
            .with_description("Implement breach notification procedures")
            .with_domain("11").with_priority(5))
        // Business Continuity
        .with_control(Control::new("12.a", "Business Continuity Plan")
            .with_description("Develop and implement business continuity plans")
            .with_domain("12").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.308(a)(7)", "Contingency Plan", MappingStrength::Strong)))
        // Privacy Practices
        .with_control(Control::new("13.a", "Privacy Notice")
            .with_description("Provide notice of privacy practices")
            .with_domain("13").with_priority(5))
        .with_control(Control::new("13.d", "Minimum Necessary")
            .with_description("Limit PHI disclosure to minimum necessary")
            .with_domain("13").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.502(b)", "Minimum Necessary", MappingStrength::Strong)))
}
