//! ISO 22301 - Business Continuity Management Systems
//!
//! International standard for business continuity.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the ISO 22301 framework definition
pub fn create_framework() -> Framework {
    Framework::new("iso22301", "ISO 22301", FrameworkCategory::SecurityStandards)
        .with_description("Business Continuity Management Systems - Requirements")
        .with_version("2019")
        .with_url("https://www.iso.org/standard/75106.html")
        // ISO 22301 Clauses
        .with_domain(FrameworkDomain::new("4", "Context of the Organization").with_order(1))
        .with_domain(FrameworkDomain::new("5", "Leadership").with_order(2))
        .with_domain(FrameworkDomain::new("6", "Planning").with_order(3))
        .with_domain(FrameworkDomain::new("7", "Support").with_order(4))
        .with_domain(FrameworkDomain::new("8", "Operation").with_order(5))
        .with_domain(FrameworkDomain::new("9", "Performance Evaluation").with_order(6))
        .with_domain(FrameworkDomain::new("10", "Improvement").with_order(7))
        // Context of the Organization
        .with_control(Control::new("4.1", "Understanding the Organization")
            .with_description("Determine external and internal issues relevant to BCMS")
            .with_domain("4").with_priority(4)
            .with_mapping(ControlMapping::new("iso27001", "4.1", "Context", MappingStrength::Strong)))
        .with_control(Control::new("4.2", "Interested Parties")
            .with_description("Determine interested parties and their requirements")
            .with_domain("4").with_priority(4))
        .with_control(Control::new("4.2.2", "Legal and Regulatory Requirements")
            .with_description("Identify applicable legal and regulatory requirements")
            .with_domain("4").with_priority(5))
        .with_control(Control::new("4.3", "BCMS Scope")
            .with_description("Determine the scope of the business continuity management system")
            .with_domain("4").with_priority(5))
        .with_control(Control::new("4.4", "BCMS")
            .with_description("Establish, implement, maintain and improve the BCMS")
            .with_domain("4").with_priority(5))
        // Leadership
        .with_control(Control::new("5.1", "Leadership and Commitment")
            .with_description("Top management shall demonstrate leadership for the BCMS")
            .with_domain("5").with_priority(5))
        .with_control(Control::new("5.2", "Policy")
            .with_description("Establish a business continuity policy")
            .with_domain("5").with_priority(5))
        .with_control(Control::new("5.3", "Roles and Responsibilities")
            .with_description("Assign and communicate BCMS roles and responsibilities")
            .with_domain("5").with_priority(4))
        // Planning
        .with_control(Control::new("6.1", "Actions to Address Risks")
            .with_description("Determine risks and opportunities for the BCMS")
            .with_domain("6").with_priority(5)
            .with_mapping(ControlMapping::new("coso", "PER-1", "Risk Identification", MappingStrength::Strong)))
        .with_control(Control::new("6.2", "Business Continuity Objectives")
            .with_description("Establish measurable business continuity objectives")
            .with_domain("6").with_priority(4))
        .with_control(Control::new("6.3", "Planning Changes to BCMS")
            .with_description("Plan changes to the BCMS systematically")
            .with_domain("6").with_priority(3))
        // Support
        .with_control(Control::new("7.1", "Resources")
            .with_description("Determine and provide resources for BCMS")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.2", "Competence")
            .with_description("Determine necessary competence for BCMS")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.3", "Awareness")
            .with_description("Ensure awareness of business continuity policy")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.4", "Communication")
            .with_description("Determine internal and external BCMS communications")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.5", "Documented Information")
            .with_description("Include documented information required by BCMS")
            .with_domain("7").with_priority(4))
        // Operation
        .with_control(Control::new("8.1", "Operational Planning and Control")
            .with_description("Plan, implement and control BCMS processes")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.2", "Business Impact Analysis")
            .with_description("Implement and maintain BIA process")
            .with_domain("8").with_priority(5)
            .with_mapping(ControlMapping::new("cobit", "DSS04", "Business Continuity", MappingStrength::Strong)))
        .with_control(Control::new("8.2.2", "Impact Assessment")
            .with_description("Assess impacts of disruption to prioritized activities")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.2.3", "Recovery Timeframes")
            .with_description("Determine prioritized timeframes for resuming activities")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.3", "Risk Assessment")
            .with_description("Implement and maintain risk assessment process")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.4", "Business Continuity Strategies")
            .with_description("Determine and select business continuity strategies")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.4.2", "Resource Requirements")
            .with_description("Determine resource requirements for strategies")
            .with_domain("8").with_priority(4))
        .with_control(Control::new("8.4.3", "Protection of Resources")
            .with_description("Implement measures to protect prioritized activities")
            .with_domain("8").with_priority(4))
        .with_control(Control::new("8.5", "Business Continuity Plans")
            .with_description("Establish and implement business continuity plans")
            .with_domain("8").with_priority(5)
            .with_mapping(ControlMapping::new("hipaa", "164.308(a)(7)", "Contingency Plan", MappingStrength::Strong)))
        .with_control(Control::new("8.5.2", "Incident Response Structure")
            .with_description("Establish incident response structure")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.5.3", "Warning and Communication")
            .with_description("Establish procedures for warning and communication")
            .with_domain("8").with_priority(4))
        .with_control(Control::new("8.6", "Exercise and Testing")
            .with_description("Exercise and test business continuity procedures")
            .with_domain("8").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "CP-4", "Contingency Plan Testing", MappingStrength::Strong)))
        // Performance Evaluation
        .with_control(Control::new("9.1", "Monitoring and Evaluation")
            .with_description("Monitor, measure, analyze and evaluate BCMS")
            .with_domain("9").with_priority(4))
        .with_control(Control::new("9.1.2", "Performance Evaluation")
            .with_description("Evaluate BC procedures through exercises")
            .with_domain("9").with_priority(4))
        .with_control(Control::new("9.2", "Internal Audit")
            .with_description("Conduct internal audits of the BCMS")
            .with_domain("9").with_priority(4))
        .with_control(Control::new("9.3", "Management Review")
            .with_description("Review BCMS at planned intervals")
            .with_domain("9").with_priority(4))
        // Improvement
        .with_control(Control::new("10.1", "Nonconformity and Corrective Action")
            .with_description("React to nonconformities and take corrective action")
            .with_domain("10").with_priority(4))
        .with_control(Control::new("10.2", "Continual Improvement")
            .with_description("Continually improve the BCMS")
            .with_domain("10").with_priority(4))
}
