//! ISO 42001 - Artificial Intelligence Management System
//!
//! International standard for AI management systems.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the ISO 42001 framework definition
pub fn create_framework() -> Framework {
    Framework::new("iso42001", "ISO/IEC 42001", FrameworkCategory::SecurityStandards)
        .with_description("Artificial Intelligence Management System (AIMS)")
        .with_version("2023")
        .with_url("https://www.iso.org/standard/81230.html")
        // ISO 42001 Clauses
        .with_domain(FrameworkDomain::new("4", "Context of the Organization").with_order(1))
        .with_domain(FrameworkDomain::new("5", "Leadership").with_order(2))
        .with_domain(FrameworkDomain::new("6", "Planning").with_order(3))
        .with_domain(FrameworkDomain::new("7", "Support").with_order(4))
        .with_domain(FrameworkDomain::new("8", "Operation").with_order(5))
        .with_domain(FrameworkDomain::new("9", "Performance Evaluation").with_order(6))
        .with_domain(FrameworkDomain::new("10", "Improvement").with_order(7))
        .with_domain(FrameworkDomain::new("A", "Annex A Controls").with_order(8))
        // Context of the Organization
        .with_control(Control::new("4.1", "Understanding the Organization")
            .with_description("Determine external and internal issues relevant to AI management")
            .with_domain("4").with_priority(4)
            .with_mapping(ControlMapping::new("iso27001", "4.1", "Context", MappingStrength::Strong)))
        .with_control(Control::new("4.2", "Interested Parties")
            .with_description("Determine interested parties and their requirements for AIMS")
            .with_domain("4").with_priority(4))
        .with_control(Control::new("4.3", "AIMS Scope")
            .with_description("Determine the scope of the AI management system")
            .with_domain("4").with_priority(5))
        .with_control(Control::new("4.4", "AI Management System")
            .with_description("Establish, implement, maintain and improve the AIMS")
            .with_domain("4").with_priority(5))
        // Leadership
        .with_control(Control::new("5.1", "Leadership and Commitment")
            .with_description("Top management shall demonstrate leadership for the AIMS")
            .with_domain("5").with_priority(5))
        .with_control(Control::new("5.2", "AI Policy")
            .with_description("Establish AI policy appropriate to the organization")
            .with_domain("5").with_priority(5)
            .with_mapping(ControlMapping::new("eu_ai_act", "HIGH-3", "AI Documentation", MappingStrength::Strong)))
        .with_control(Control::new("5.3", "Roles and Responsibilities")
            .with_description("Assign and communicate AIMS roles and responsibilities")
            .with_domain("5").with_priority(4))
        // Planning
        .with_control(Control::new("6.1", "Risk and Opportunity Assessment")
            .with_description("Determine AI-related risks and opportunities")
            .with_domain("6").with_priority(5)
            .with_mapping(ControlMapping::new("eu_ai_act", "HIGH-1", "Risk Management", MappingStrength::Strong)))
        .with_control(Control::new("6.1.3", "AI Risk Assessment")
            .with_description("Perform AI system risk assessment including potential harms")
            .with_domain("6").with_priority(5))
        .with_control(Control::new("6.1.4", "AI Risk Treatment")
            .with_description("Determine risk treatment for AI-related risks")
            .with_domain("6").with_priority(5))
        .with_control(Control::new("6.2", "AI Objectives")
            .with_description("Establish measurable AI objectives")
            .with_domain("6").with_priority(4))
        .with_control(Control::new("6.3", "Planning of Changes")
            .with_description("Plan changes to the AIMS systematically")
            .with_domain("6").with_priority(4))
        // Support
        .with_control(Control::new("7.1", "Resources")
            .with_description("Provide resources needed for the AIMS")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.2", "Competence")
            .with_description("Ensure persons have necessary AI competence")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.3", "Awareness")
            .with_description("Ensure awareness of AI policy and AIMS requirements")
            .with_domain("7").with_priority(4))
        .with_control(Control::new("7.4", "Communication")
            .with_description("Determine internal and external AIMS communications")
            .with_domain("7").with_priority(3))
        .with_control(Control::new("7.5", "Documented Information")
            .with_description("Include documented information required for AIMS")
            .with_domain("7").with_priority(4))
        // Operation
        .with_control(Control::new("8.1", "Operational Planning")
            .with_description("Plan, implement and control processes for AIMS")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.2", "AI Risk Assessment")
            .with_description("Perform AI risk assessment at planned intervals")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.3", "AI Risk Treatment")
            .with_description("Implement AI risk treatment plan")
            .with_domain("8").with_priority(5))
        .with_control(Control::new("8.4", "AI System Impact Assessment")
            .with_description("Assess impact of AI systems on individuals and society")
            .with_domain("8").with_priority(5)
            .with_mapping(ControlMapping::new("eu_ai_act", "HIGH-6", "Human Oversight", MappingStrength::Strong)))
        // Performance Evaluation
        .with_control(Control::new("9.1", "Monitoring and Measurement")
            .with_description("Monitor, measure, analyze and evaluate AIMS")
            .with_domain("9").with_priority(4))
        .with_control(Control::new("9.2", "Internal Audit")
            .with_description("Conduct internal audits of the AIMS")
            .with_domain("9").with_priority(4)
            .with_mapping(ControlMapping::new("iso27001", "9.2", "Internal Audit", MappingStrength::Strong)))
        .with_control(Control::new("9.3", "Management Review")
            .with_description("Review AIMS at planned intervals")
            .with_domain("9").with_priority(4))
        // Improvement
        .with_control(Control::new("10.1", "Continual Improvement")
            .with_description("Continually improve the AIMS")
            .with_domain("10").with_priority(4))
        .with_control(Control::new("10.2", "Nonconformity and Corrective Action")
            .with_description("React to nonconformities and take corrective action")
            .with_domain("10").with_priority(4))
        // Annex A Controls
        .with_control(Control::new("A.2.2", "AI System Lifecycle")
            .with_description("Manage AI system through its complete lifecycle")
            .with_domain("A").with_priority(5))
        .with_control(Control::new("A.3.2", "Data Quality")
            .with_description("Ensure quality of data used in AI systems")
            .with_domain("A").with_priority(5)
            .with_mapping(ControlMapping::new("eu_ai_act", "HIGH-2", "Data Governance", MappingStrength::Strong)))
        .with_control(Control::new("A.4.4", "Explainability")
            .with_description("Ensure AI system decisions can be explained")
            .with_domain("A").with_priority(5))
        .with_control(Control::new("A.5.3", "Human Oversight")
            .with_description("Ensure appropriate human oversight of AI systems")
            .with_domain("A").with_priority(5))
        .with_control(Control::new("A.6.2", "Bias and Fairness")
            .with_description("Address bias and ensure fairness in AI systems")
            .with_domain("A").with_priority(5))
        .with_control(Control::new("A.8.2", "AI System Security")
            .with_description("Protect AI systems from security threats")
            .with_domain("A").with_priority(5)
            .with_mapping(ControlMapping::new("iso27001", "A.12", "Operations Security", MappingStrength::Strong)))
}
