//! NIST SP 800-171 - Protecting Controlled Unclassified Information
//!
//! Security requirements for protecting CUI in nonfederal systems.

use crate::framework::{Framework, FrameworkCategory, FrameworkDomain};
use crate::control::Control;
use crate::mapping::{ControlMapping, MappingStrength};

/// Create the NIST 800-171 framework definition
pub fn create_framework() -> Framework {
    Framework::new("nist_800_171", "NIST SP 800-171", FrameworkCategory::UsGovernment)
        .with_description("Protecting Controlled Unclassified Information in Nonfederal Systems")
        .with_version("Rev 2")
        .with_url("https://csrc.nist.gov/publications/detail/sp/800-171/rev-2/final")
        // 14 Control Families
        .with_domain(FrameworkDomain::new("AC", "Access Control").with_order(1))
        .with_domain(FrameworkDomain::new("AT", "Awareness and Training").with_order(2))
        .with_domain(FrameworkDomain::new("AU", "Audit and Accountability").with_order(3))
        .with_domain(FrameworkDomain::new("CM", "Configuration Management").with_order(4))
        .with_domain(FrameworkDomain::new("IA", "Identification and Authentication").with_order(5))
        .with_domain(FrameworkDomain::new("IR", "Incident Response").with_order(6))
        .with_domain(FrameworkDomain::new("MA", "Maintenance").with_order(7))
        .with_domain(FrameworkDomain::new("MP", "Media Protection").with_order(8))
        .with_domain(FrameworkDomain::new("PS", "Personnel Security").with_order(9))
        .with_domain(FrameworkDomain::new("PE", "Physical Protection").with_order(10))
        .with_domain(FrameworkDomain::new("RA", "Risk Assessment").with_order(11))
        .with_domain(FrameworkDomain::new("CA", "Security Assessment").with_order(12))
        .with_domain(FrameworkDomain::new("SC", "System and Communications Protection").with_order(13))
        .with_domain(FrameworkDomain::new("SI", "System and Information Integrity").with_order(14))
        // Access Control (22 requirements)
        .with_control(Control::new("3.1.1", "Limit System Access")
            .with_description("Limit system access to authorized users, processes acting on behalf of authorized users, and devices")
            .with_domain("AC").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "AC-2", "Account Management", MappingStrength::Strong))
            .with_mapping(ControlMapping::new("cmmc", "AC.L1-3.1.1", "Authorized Access", MappingStrength::Strong)))
        .with_control(Control::new("3.1.2", "Limit Transaction Access")
            .with_description("Limit system access to the types of transactions and functions that authorized users are permitted to execute")
            .with_domain("AC").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "AC-3", "Access Enforcement", MappingStrength::Strong)))
        .with_control(Control::new("3.1.3", "Control CUI Flow")
            .with_description("Control the flow of CUI in accordance with approved authorizations")
            .with_domain("AC").with_priority(4))
        .with_control(Control::new("3.1.4", "Separation of Duties")
            .with_description("Separate the duties of individuals to reduce the risk of malevolent activity")
            .with_domain("AC").with_priority(4))
        .with_control(Control::new("3.1.5", "Least Privilege")
            .with_description("Employ the principle of least privilege, including for specific security functions")
            .with_domain("AC").with_priority(5))
        // Audit and Accountability
        .with_control(Control::new("3.3.1", "System Auditing")
            .with_description("Create and retain system audit logs and records to enable monitoring, analysis, investigation, and reporting")
            .with_domain("AU").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "AU-2", "Audit Events", MappingStrength::Strong)))
        .with_control(Control::new("3.3.2", "User Accountability")
            .with_description("Ensure that the actions of individual system users can be uniquely traced")
            .with_domain("AU").with_priority(5))
        // Configuration Management
        .with_control(Control::new("3.4.1", "System Baselines")
            .with_description("Establish and maintain baseline configurations and inventories of organizational systems")
            .with_domain("CM").with_priority(4)
            .with_mapping(ControlMapping::new("nist_800_53", "CM-2", "Baseline Configuration", MappingStrength::Strong)))
        .with_control(Control::new("3.4.2", "Security Settings")
            .with_description("Establish and enforce security configuration settings for IT products")
            .with_domain("CM").with_priority(4))
        // Identification and Authentication
        .with_control(Control::new("3.5.1", "User Identification")
            .with_description("Identify information system users, processes acting on behalf of users, or devices")
            .with_domain("IA").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "IA-2", "Identification and Authentication", MappingStrength::Strong)))
        .with_control(Control::new("3.5.2", "User Authentication")
            .with_description("Authenticate (or verify) the identities of those users, processes, or devices")
            .with_domain("IA").with_priority(5))
        .with_control(Control::new("3.5.3", "Multifactor Authentication")
            .with_description("Use multifactor authentication for local and network access")
            .with_domain("IA").with_priority(5))
        // Incident Response
        .with_control(Control::new("3.6.1", "Incident Handling")
            .with_description("Establish an operational incident-handling capability")
            .with_domain("IR").with_priority(4)
            .with_mapping(ControlMapping::new("nist_800_53", "IR-4", "Incident Handling", MappingStrength::Strong)))
        .with_control(Control::new("3.6.2", "Incident Reporting")
            .with_description("Track, document, and report incidents to designated officials")
            .with_domain("IR").with_priority(4))
        // System and Communications Protection
        .with_control(Control::new("3.13.1", "Boundary Protection")
            .with_description("Monitor, control, and protect organizational communications at external boundaries")
            .with_domain("SC").with_priority(5)
            .with_mapping(ControlMapping::new("nist_800_53", "SC-7", "Boundary Protection", MappingStrength::Strong)))
        .with_control(Control::new("3.13.8", "Data at Rest Protection")
            .with_description("Implement cryptographic mechanisms to prevent unauthorized disclosure of CUI")
            .with_domain("SC").with_priority(5))
        .with_control(Control::new("3.13.11", "FIPS Cryptography")
            .with_description("Employ FIPS-validated cryptography when used to protect confidentiality of CUI")
            .with_domain("SC").with_priority(5))
        // System and Information Integrity
        .with_control(Control::new("3.14.1", "Flaw Remediation")
            .with_description("Identify, report, and correct information and system flaws in a timely manner")
            .with_domain("SI").with_priority(4)
            .with_mapping(ControlMapping::new("nist_800_53", "SI-2", "Flaw Remediation", MappingStrength::Strong)))
        .with_control(Control::new("3.14.2", "Malicious Code Protection")
            .with_description("Provide protection from malicious code at appropriate locations")
            .with_domain("SI").with_priority(5))
        .with_control(Control::new("3.14.6", "Security Alerts")
            .with_description("Monitor organizational systems for unauthorized access and connections")
            .with_domain("SI").with_priority(4))
}
