#!/usr/bin/env bash
# scripts/deploy-server-prod.sh — Production nexus-server deployment.
#
# Builds nexus-server from source, ships it to a remote C2 host (or
# localhost), creates the nexus system user and directory layout, installs
# mTLS certs, writes the systemd EnvironmentFile, installs the service unit,
# initialises the NodeIdentity on first run, and starts the service.
#
# Tested on Ubuntu/Debian targets. The remote host must have sudo and sshd.
#
# Usage:
#   ./scripts/deploy-server-prod.sh --remote user@host [options]
#   ./scripts/deploy-server-prod.sh --local            [options]
#
# Options:
#   --remote user@host   Deploy to a remote host over SSH
#   --local              Deploy to localhost (needs sudo)
#   --cert-dir DIR       Local dir with prod certs (default: ./certs/prod)
#                        Must contain: ca.crt.pem, server.crt.pem, server.key.pem
#   --config FILE        Path to nexus.toml to ship (default: nexus.toml.example)
#   --ssh-key FILE       SSH identity file (passed as -i FILE to ssh/scp)
#   --no-build           Skip cargo build; use existing target/release/nexus-server
#   --build-only         Build and copy binary; skip user/cert/service setup
#   --restart            Restart a running service after a binary upgrade (implies --no-build=false)
#
# Env overrides:
#   CERT_DIR             Same as --cert-dir
#   NEXUS_CONFIG         Same as --config
#   SSH_KEY              Same as --ssh-key
#
# Prerequisites:
#   - Certs already generated by scripts/gen-certs-prod.sh (--cert-dir)
#   - Remote host: reachable via SSH, apt-based (Debian/Ubuntu)
#   - Local: Rust toolchain (cargo), protobuf-compiler, pkg-config, libssl-dev

set -euo pipefail

for _cb in \
    "${CARGO_HOME:+${CARGO_HOME}/bin}" \
    "${HOME:-}/.cargo/bin" \
    "/root/.cargo/bin" \
    "/usr/local/cargo/bin"; do
    [[ -n "$_cb" && -d "$_cb" && ":${PATH}:" != *":${_cb}:"* ]] && PATH="${_cb}:${PATH}"
done
export PATH

# ---------- paths ----------
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CERT_DIR="${CERT_DIR:-${REPO_ROOT}/certs/prod}"
NEXUS_CONFIG="${NEXUS_CONFIG:-${REPO_ROOT}/nexus.toml}"
SERVICE_UNIT="${REPO_ROOT}/docs/deployment/examples/nexus-server.service"
CAPABILITIES_EXAMPLE="${REPO_ROOT}/config/capabilities.json"
BINARY="${REPO_ROOT}/target/release/nexus-server"

# ---------- flags ----------
REMOTE=""      # user@host, empty → local
DO_BUILD=1
DO_SETUP=1     # create user/dirs/certs/service
DO_RESTART=0
SSH_KEY="${SSH_KEY:-}"

for arg in "$@"; do :; done  # forward-declare so `shift` works in while loop
while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote)     REMOTE="$2"; shift 2 ;;
        --local)      REMOTE=""; shift ;;
        --cert-dir)   CERT_DIR="$2"; shift 2 ;;
        --config)     NEXUS_CONFIG="$2"; shift 2 ;;
        --ssh-key)    SSH_KEY="$2"; shift 2 ;;
        --no-build)   DO_BUILD=0; shift ;;
        --build-only) DO_SETUP=0; shift ;;
        --restart)    DO_RESTART=1; shift ;;
        -h|--help)
            grep '^#' "$0" | sed 's/^# \{0,1\}//'
            exit 0
            ;;
        *) echo "unknown flag: $1" >&2; exit 2 ;;
    esac
done

# ---------- helpers ----------
log()  { printf '\033[1;34m[server-deploy]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[server-deploy]\033[0m %s\n' "$*" >&2; }
die()  { printf '\033[1;31m[server-deploy]\033[0m %s\n' "$*" >&2; exit 1; }

need_cmd() { command -v "$1" >/dev/null 2>&1; }

# Build the ssh/scp option arrays.
SSH_OPTS=(-o StrictHostKeyChecking=no -o BatchMode=yes)
SCP_OPTS=()
if [[ -n "$SSH_KEY" ]]; then
    SSH_OPTS+=(-i "$SSH_KEY")
    SCP_OPTS+=(-i "$SSH_KEY")
fi

# rsh / rsudo: run a command, either remotely or locally with sudo.
rsh() {
    if [[ -n "$REMOTE" ]]; then
        ssh "${SSH_OPTS[@]}" "$REMOTE" "$@"
    else
        sudo "$@"
    fi
}

# rscp SRC DEST: copy a local file to the target (remote or local via cp/install).
rscp() {
    local src="$1" dest="$2"
    if [[ -n "$REMOTE" ]]; then
        scp "${SCP_OPTS[@]}" "$src" "${REMOTE}:${dest}"
    else
        sudo cp "$src" "$dest"
    fi
}

# ---------- 1. validate local cert dir ----------
log "validating certs in ${CERT_DIR}"
for f in ca.crt.pem server.crt.pem server.key.pem; do
    [[ -r "${CERT_DIR}/${f}" ]] || die "missing cert: ${CERT_DIR}/${f}
Run: ./scripts/gen-certs-prod.sh --domain <c2-domain> --ip <c2-ip> --out ${CERT_DIR}"
done
log "certs OK"

# ---------- 2. validate config ----------
[[ -r "$NEXUS_CONFIG" ]] || die "nexus config not found: ${NEXUS_CONFIG}"
if [[ "$NEXUS_CONFIG" == *.example ]]; then
    warn "deploying example config (${NEXUS_CONFIG}) — update /etc/nexus/nexus.toml on the target host"
fi

# ---------- 3. validate service unit ----------
[[ -r "$SERVICE_UNIT" ]] || die "service unit not found: ${SERVICE_UNIT}"

# ---------- 4. build ----------
if [[ "$DO_BUILD" -eq 1 ]]; then
    log "checking local build deps"
    need_cmd cargo  || die "cargo not on PATH — install rustup"
    need_cmd pkg-config || warn "pkg-config not found — build may fail"

    BUILD_PKGS=(build-essential pkg-config libssl-dev protobuf-compiler)
    MISSING_PKGS=()
    for p in "${BUILD_PKGS[@]}"; do
        dpkg -s "$p" >/dev/null 2>&1 || MISSING_PKGS+=("$p")
    done
    if [[ ${#MISSING_PKGS[@]} -gt 0 ]]; then
        log "installing missing build packages: ${MISSING_PKGS[*]}"
        sudo apt-get update -qq
        sudo apt-get install -y "${MISSING_PKGS[@]}"
    fi

    log "building nexus-server (release)"
    cargo build --release -p nexus-infra --bin nexus-server \
        --manifest-path "${REPO_ROOT}/Cargo.toml"
    log "build complete: ${BINARY}"
fi

[[ -x "$BINARY" ]] || die "binary not found or not executable: ${BINARY}
Run without --no-build, or check cargo build output."

# ---------- 5. server setup (user, dirs, certs, config, service) ----------
if [[ "$DO_SETUP" -eq 1 ]]; then

    # 5a. system user
    log "creating nexus system user (if absent)"
    rsh bash -c 'id nexus >/dev/null 2>&1 || useradd --system --no-create-home --shell /usr/sbin/nologin nexus'

    # 5b. directory layout
    log "creating directory layout"
    rsh bash -c '
        mkdir -p /etc/nexus /var/lib/nexus /var/log/nexus
        chown -R nexus:nexus /var/lib/nexus /var/log/nexus
        chown root:nexus /etc/nexus
        chmod 750 /etc/nexus
    '

    # 5c. binary
    log "installing binary → /usr/local/bin/nexus-server"
    if [[ -n "$REMOTE" ]]; then
        scp "${SCP_OPTS[@]}" "$BINARY" "${REMOTE}:/tmp/nexus-server"
        rsh install -m 0755 -o root -g root /tmp/nexus-server /usr/local/bin/nexus-server
        rsh rm -f /tmp/nexus-server
    else
        sudo install -m 0755 -o root -g root "$BINARY" /usr/local/bin/nexus-server
    fi

    # 5d. certs
    log "installing mTLS certs into /etc/nexus/"
    if [[ -n "$REMOTE" ]]; then
        scp "${SCP_OPTS[@]}" \
            "${CERT_DIR}/ca.crt.pem" \
            "${CERT_DIR}/server.crt.pem" \
            "${CERT_DIR}/server.key.pem" \
            "${REMOTE}:/tmp/"
        rsh bash -c '
            install -m 0644 -o root  -g nexus /tmp/ca.crt.pem     /etc/nexus/ca.crt.pem
            install -m 0644 -o root  -g nexus /tmp/server.crt.pem /etc/nexus/server.crt.pem
            install -m 0600 -o nexus -g nexus /tmp/server.key.pem /etc/nexus/server.key.pem
            shred -u /tmp/server.key.pem
            rm -f /tmp/ca.crt.pem /tmp/server.crt.pem
        '
    else
        sudo install -m 0644 -o root  -g nexus "${CERT_DIR}/ca.crt.pem"     /etc/nexus/ca.crt.pem
        sudo install -m 0644 -o root  -g nexus "${CERT_DIR}/server.crt.pem" /etc/nexus/server.crt.pem
        sudo install -m 0600 -o nexus -g nexus "${CERT_DIR}/server.key.pem" /etc/nexus/server.key.pem
    fi

    # 5e. server.env
    log "writing /etc/nexus/server.env"
    rsh bash -c "cat > /etc/nexus/server.env << 'ENVEOF'
NEXUS_CA_CERT=/etc/nexus/ca.crt.pem
NEXUS_SERVER_CERT=/etc/nexus/server.crt.pem
NEXUS_SERVER_KEY=/etc/nexus/server.key.pem
RUST_LOG=info
ENVEOF
chown root:nexus /etc/nexus/server.env
chmod 640 /etc/nexus/server.env"

    # 5f. nexus.toml (skip if already present to avoid clobbering live config)
    log "installing nexus.toml (skips if already present)"
    if [[ -n "$REMOTE" ]]; then
        scp "${SCP_OPTS[@]}" "$NEXUS_CONFIG" "${REMOTE}:/tmp/nexus.toml.deploy"
        rsh bash -c '
            if [[ ! -f /etc/nexus/nexus.toml ]]; then
                install -m 0640 -o root -g nexus /tmp/nexus.toml.deploy /etc/nexus/nexus.toml
                echo "[server-deploy] nexus.toml installed — review /etc/nexus/nexus.toml"
            else
                echo "[server-deploy] nexus.toml already present — not overwritten"
            fi
            rm -f /tmp/nexus.toml.deploy
        '
    else
        if [[ ! -f /etc/nexus/nexus.toml ]]; then
            sudo install -m 0640 -o root -g nexus "$NEXUS_CONFIG" /etc/nexus/nexus.toml
            warn "nexus.toml installed from example — review /etc/nexus/nexus.toml before use"
        else
            log "nexus.toml already present — not overwritten"
        fi
    fi

    # 5g. capabilities.json (skip if already present)
    log "installing capabilities.json (skips if already present)"
    if [[ -r "$CAPABILITIES_EXAMPLE" ]]; then
        if [[ -n "$REMOTE" ]]; then
            scp "${SCP_OPTS[@]}" "$CAPABILITIES_EXAMPLE" "${REMOTE}:/tmp/capabilities.json.deploy"
            rsh bash -c '
                if [[ ! -f /etc/nexus/capabilities.json ]]; then
                    install -m 0644 -o root -g nexus /tmp/capabilities.json.deploy /etc/nexus/capabilities.json
                fi
                rm -f /tmp/capabilities.json.deploy
            '
        else
            if [[ ! -f /etc/nexus/capabilities.json ]]; then
                sudo install -m 0644 -o root -g nexus "$CAPABILITIES_EXAMPLE" /etc/nexus/capabilities.json
                warn "capabilities.json installed from example — add agent peer-ids before enabling"
            else
                log "capabilities.json already present — not overwritten"
            fi
        fi
    else
        warn "capabilities.example.json not found at ${CAPABILITIES_EXAMPLE} — skipping"
    fi

    # 5h. systemd unit
    log "installing nexus-server.service"
    if [[ -n "$REMOTE" ]]; then
        scp "${SCP_OPTS[@]}" "$SERVICE_UNIT" "${REMOTE}:/tmp/nexus-server.service"
        rsh bash -c '
            install -m 0644 -o root -g root /tmp/nexus-server.service /etc/systemd/system/nexus-server.service
            rm -f /tmp/nexus-server.service
            systemctl daemon-reload
            systemctl enable nexus-server
        '
    else
        sudo install -m 0644 -o root -g root "$SERVICE_UNIT" /etc/systemd/system/nexus-server.service
        sudo systemctl daemon-reload
        sudo systemctl enable nexus-server
    fi

    # 5i. NodeIdentity (first-run only — safe to skip if file already exists)
    log "initialising NodeIdentity (skipped if already present)"
    rsh bash -c '
        if [[ ! -f /var/lib/nexus/server-identity.bin ]]; then
            nexus-server --init-identity /var/lib/nexus/server-identity.bin
            chmod 600 /var/lib/nexus/server-identity.bin
            chown nexus:nexus /var/lib/nexus/server-identity.bin
            echo "[server-deploy] NodeIdentity created"
        else
            echo "[server-deploy] NodeIdentity already present — not regenerated"
        fi
    ' || warn "--init-identity flag not supported by this binary — initialise manually:
  sudo -u nexus nexus-server --init-identity /var/lib/nexus/server-identity.bin
  sudo chmod 600 /var/lib/nexus/server-identity.bin"

fi  # DO_SETUP

# ---------- 6. start / restart ----------
if [[ "$DO_SETUP" -eq 1 || "$DO_RESTART" -eq 1 ]]; then
    log "starting nexus-server"
    rsh systemctl restart nexus-server

    # Give it a moment to settle, then check status.
    sleep 3
    if rsh systemctl is-active --quiet nexus-server; then
        log "nexus-server is running"
    else
        warn "nexus-server failed to start — check journal:"
        rsh journalctl -u nexus-server --since "1 minute ago" --no-pager -n 30 || true
        die "service did not start cleanly"
    fi
fi

# ---------- 7. smoke test ----------
if [[ "$DO_SETUP" -eq 1 || "$DO_RESTART" -eq 1 ]]; then
    log "smoke test: checking journal for A2A startup line"
    if rsh journalctl -u nexus-server --since "1 minute ago" --no-pager -n 50 2>/dev/null \
        | grep -q "A2A server starting"; then
        log "A2A server startup confirmed in journal"
    else
        warn "A2A startup log line not found — server may still be initialising"
        warn "Run: journalctl -u nexus-server -f"
    fi
fi

# ---------- summary ----------
cat <<EOF

[server-deploy] deployment complete.

Files on target:
  /usr/local/bin/nexus-server     — binary
  /etc/nexus/nexus.toml           — config   (REVIEW and customise)
  /etc/nexus/capabilities.json    — capability matrix (ADD agent peer-ids)
  /etc/nexus/server.env           — mTLS env vars
  /etc/nexus/ca.crt.pem           — CA cert
  /etc/nexus/server.crt.pem       — server cert
  /etc/nexus/server.key.pem       — server key (0600)
  /var/lib/nexus/server-identity.bin — NodeIdentity (0600)
  /var/lib/nexus/audit.log        — hash-chained audit log (created at runtime)

Next steps:
  1. Review /etc/nexus/nexus.toml — set [a2a].bind, [audit], [rate_limit], etc.
  2. Add agent peer-ids to /etc/nexus/capabilities.json, then:
       sudo systemctl restart nexus-server
  3. Distribute certs to operator workstations:
       ${CERT_DIR}/ca.crt.pem
       ${CERT_DIR}/operator.crt.pem  (and operator.key.pem)
  4. Verify mTLS handshake from an operator box:
       openssl s_client -connect <host>:50052 -servername <domain> \\
           -CAfile ${CERT_DIR}/ca.crt.pem \\
           -cert   ${CERT_DIR}/operator.crt.pem \\
           -key    ${CERT_DIR}/operator.key.pem </dev/null 2>&1 | tail -5
  5. Check audit log integrity once agents connect:
       sudo tail /var/lib/nexus/audit.log

EOF
